version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - .env
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./hleb:/hleb
      - ./log:/log
    ports:
      - "${SERVER_EXTERNAL_PORT}:80"

  php:
    environment:
      PHP_IDE_CONFIG: "serverName=toaster"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./hleb:/hleb
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  db:
    image: mariadb
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "${DATABASE_EXTERNAL_PORT}:3306"

  pma:
    image: phpmyadmin
    env_file:
      - .env
    ports:
      - "${PMA_EXTERNAL_PORT}:80"
