version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./hleb:/hleb
      - ./log:/log
    ports:
      - '5125:80'

  php:
    build: ./docker
    environment:
      PHP_IDE_CONFIG: "serverName=toaster"
    volumes:
      - ./hleb:/hleb
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hleb
      MYSQL_USER: hleb
      MYSQL_PASSWORD: toaster
      MARIADB_RANDOM_ROOT_PASSWORD: ok
    ports:
      - '3306:3306'

  pma:
    image: phpmyadmin
    environment:
      PMA_USER: hleb
      PMA_PASSWORD: toaster
    ports:
      - '8080:80'
